import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <nav className="flex text-white flex-row justify-between items-center bg-gray-700 p-4">
        Navbar
      </nav>
      <main>{children}</main>
    </html>
  )
}
